[theme]
base                     = "dark"
primaryColor             = "#C9A84C"
backgroundColor          = "#0C0820"
secondaryBackgroundColor = "#160F2E"
textColor                = "#F5EFE0"
font                     = "sans serif"

[server]
headless             = true
enableCORS           = false
enableXsrfProtection = false
maxUploadSize        = 50

[browser]
gatherUsageStats = false
